---
apiVersion: v1
kind: Namespace
metadata:
  name: dunnu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dunnu-frontend
  namespace: dunnu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dunnu-frontend
  template:
    metadata:
      labels:
        app: dunnu-frontend
    spec:
      containers:
      - name: dunnu-frontend
        image: iaminnocent/dunnu
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: dunnu-service
  namespace: dunnu
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: my-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30043
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: dunnu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: admin

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: postgres
  namespace: dunnu
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  # Sets name of PVC
  labels:
    app: postgres
  namespace: dunnu
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dunnu
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
