name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  PREVIOUS_IMAGE_VERSION: latest
  RETAG_VERSION: 1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t dunnu:new .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Re-Tag Previous Docker Image
        run: docker pull ${{ env.DOCKER_USERNAME }}/dunnu:${{ env.PREVIOUS_IMAGE_VERSION }} && docker tag ${{ env.DOCKER_USERNAME }}/dunnu:${{ env.PREVIOUS_IMAGE_VERSION }} ${{ env.DOCKER_USERNAME }}/dunnu:${{ env.RETAG_VERSION }}
      - name: Tag New Docker Image as latest
        run: docker tag dunnu:new ${{ env.DOCKER_USERNAME }}/dunnu:${{ env.PREVIOUS_IMAGE_VERSION }}
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ env.DOCKER_USERNAME }}/dunnu:${{ env.PREVIOUS_IMAGE_VERSION }} && docker push ${{ env.DOCKER_USERNAME }}/dunnu:${{ env.RETAG_VERSION }}
